Make it a react app
unhappyfolk/unhappyfolk.github.io pull request #6
Opened 2022-02-19 02:10 UTC by yossef-khaled

2022-02-19 03:08 UTC, yossef-khaled commented
There is a conflict, but I don't know why?

2022-02-19 09:19 UTC, mhashim6 commented
for #2

2022-02-19 10:01 UTC, mhashim6 requested changes

2022-02-19 10:01 UTC, mhashim6 commented on src/assets/compressed-logo.svg
> +<svg xml:space="preserve" viewBox="0 0 800 800" xmlns="http://www.w3.org/2000/svg"><path style="fill:#ceaa37;stroke:none;stroke-width:1.07481" d="M78.646 19.604c8.631 12.151 24.273 19.197 37.619 24.8
Lovely!

2022-02-19 10:01 UTC, mhashim6 commented on src/Components/Home/Home.jsx
> +              <p class="subtitle">Timeless, Placeless Projects.</p>
Please remove "projects".

2022-02-19 15:03 UTC, yossef-khaled commented
What do you mean ?

2022-02-19 15:19 UTC, mhashim6 commented
> What do you mean by for #2 ?

Referencing the issue number to link with this PR.

2022-02-20 06:18 UTC, mhashim6 approved these changes

2022-02-20 06:24 UTC, mhashim6 requested changes
please also remove logo.svg and rename compressed-logo.svg

2022-02-20 06:24 UTC, mhashim6 commented on public/index.html
> +    <link rel="stylesheet" href="../src/index.css" type="text/css" />
please put index.css in the same folder.

2022-02-20 08:24 UTC, mhashim6 commented
@yossef-khaled please commit `yarn.lock`

2022-02-20 20:26 UTC, yossef-khaled commented
I am not using yarn.

2022-02-20 20:42 UTC, yossef-khaled commented
I was trying to pull your changes locally, but turned out with this last commit !!

2022-02-21 04:11 UTC, mhashim6 commented
> I am not using yarn.

You should!

2022-02-21 04:13 UTC, mhashim6 commented
> I was trying to pull your last commit locally, but turned out with this last commit !!

That's completely normal.

2022-02-22 04:11 UTC, mhashim6 approved these changes

2022-02-22 04:14 UTC, mhashim6 commented on public/index.html
> +    <link rel="stylesheet" href="../src/index.css" type="text/css" />
@yossef-khaled

2022-02-23 14:55 UTC, mhashim6 commented
@yossef-khaled please look at the last commit.

2022-02-23 23:00 UTC, yossef-khaled commented
Really ??

2022-02-24 11:10 UTC, mhashim6 commented
A brilliant job! Merging.

2022-02-24 11:11 UTC, merged